######################################################################
# Automatically generated by qmake (2.01a) ? 7? 7 11:56:37 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyClass.h
SOURCES += main.cpp
